batch_size: 2
datasetname: citypersons
data_dir: ./data/citypersons
split: train
split_test: val
is_training: True
model_type: 'retinanet'
backbone: 'resnet50' # 'resnet101'
# restore: ''
display: 10
log_image: 100
data_workers: 4
use_augment: False

use_focal_loss: True
num_classes: 2 # ('__background__', 'pedestrian', 'rider', 'sitting', 'unusual', 'group')
class_activation: 'softmax'
rpn_sample_strategy: 'simple' # 'traditional', 'simple', 'advanced'
rpn_box_encoding: 'fastrcnn' # 'linear', 'fastrcnn'
rpn_bg_threshold: 0.5
rpn_fg_threshold: 0.6
min_side: 1024
max_side: 2048
canvas_width: 2048
canvas_height: 1024
training_scale: [0.3, 0.5, 0.7, 1.0]

strides: [8, 16, 32, 64, 128]
f_keys: ['C3', 'C4', 'C5', 'C6', 'C7']
in_channels: [512, 1024, 2048, 256, 256]

## finer anchors, no intersection cross layers
max_epoch: 15
weight_decay: 0.0001
lr: 0.001
lr_decay_epoches: [8, 12, 16]
#anchor_scales: [
#    [2, 2.828],
#    [4, 5.657],
#    [8, 11.314],
#    [16, 22.627],
#    [32, 45.255],
#]
#anchor_ratios: [0.333, 0.5, 1, 2.0, 3.0] # height / width
anchor_scales: [
    [2,  2.520,  3.175],
    [4,  5.040,  6.349],
    [8,  10.079, 12.700],
    [16, 20.159, 25.398],
    [32, 40.317, 50.797],
]
anchor_ratios: [1, 2.5] # height / width
anchor_base: 16
score_threshold: 0.5
max_det_num: 100
overlap_threshold: 0.5
with_segment: False

class_weights: []
segment_weights: []
start_over: False
