batch_size: 2
datasetname: pascal_voc
data_dir: ./data/pascal_voc
split: trainval_0712
split_test: test_0712
is_training: True
model_type: 'retinanet'
backbone: 'resnet101' # 'resnet101'
# restore: ''
display: 20
log_image: 200
data_workers: 2
use_augment: False

use_focal_loss: True
num_classes: 21
class_activation: 'sigmoid'
rpn_sample_strategy: 'simple' # 'traditional', 'simple', 'advanced'
rpn_box_encoding: 'fastrcnn' # 'linear', 'fastrcnn'
rpn_bg_threshold: 0.4
rpn_fg_threshold: 0.5
min_side: 600
max_side: 1000
training_scale: [0.5, 0.7, 1.0]

# for resnet50
strides: [8, 16, 32, 64, 128]
f_keys: ['C3', 'C4', 'C5', 'C6', 'C7']
in_channels: [512, 1024, 2048, 256, 256]

## finer anchors, no intersection cross layers
max_epoch: 15
weight_decay: 0.0001
lr: 0.001
lr_decay_epoches: [6, 8, 10]
anchor_scales: [
    [2, 2.828],
    [4, 5.657],
    [8, 11.314],
    [16, 22.627],
    [32, 45.255],
]
anchor_ratios: [0.333, 0.5, 1, 2.0, 3.0] # height / width
anchor_base: 16
score_threshold: 0.5
max_det_num: 100
overlap_threshold: 0.5
with_segment: False

class_weights: []
segment_weights: []
start_over: False
