batch_size: 2
datasetname: coco
data_dir: ./data/coco/
split: trainval2014
split_test: minival2014_new
is_training: True
model_type: 'maskrcnn'
backbone: 'resnet101' # 'resnet101'
# restore: ''
display: 10
log_image: 500
data_workers: 6
use_augment: False

use_focal_loss: True
num_classes: 81
class_activation: 'softmax'
rpn_sample_strategy: 'simple' # 'traditional', 'simple', 'advanced'
rpn_box_encoding: 'fastrcnn' # 'linear', 'fastrcnn'
rpn_bg_threshold: 0.3
rpn_fg_threshold: 0.6
min_side: 600
max_side: 1000

strides: [4, 8, 16, 32]
f_keys: ['C2', 'C3', 'C4', 'C5']
in_channels: [256, 512, 1024, 2048]

## finer anchors, no intersection cross layers
max_epoch: 31
weight_decay: 0.0005
lr: 0.001
lr_decay_epoches: [8, 11, 13]

anchor_scales: [
    [2, 2.828],
    [4, 5.657],
    [8, 11.314],
    [16, 22.627],
]
anchor_ratios: [0.333, 0.5, 1, 2.0, 3.0] # height / width
anchor_base: 16
score_threshold: 0.3
max_det_num: 100
overlap_threshold: 0.5
with_segment: False

class_weights: []
segment_weights: []
start_over: True
tensorboard: False
